name: CI

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly, nightly-2025-01-18]
        arch: [x86_64, riscv64, aarch64, loongarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
    - name: Setup ArceOS
      run: ./scripts/get_deps.sh
    - name: Check rust version
      run: rustc --version --verbose
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: x86_64
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: riscv64
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: aarch64
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: loongarch64
    - name: Check code format
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: cargo fmt --all -- --check
    - name: Clippy
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: make clippy ARCH=${{ matrix.arch }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64, loongarch64]
        rust-toolchain: [nightly, nightly-2025-01-18]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, llvm-tools
        targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Build for ${{ matrix.arch }}
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: make ARCH=${{ matrix.arch }} build

  test-musl:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64, loongarch64]
        rust-toolchain: [nightly-2025-01-18]
    env:
      qemu-version: 9.2.1
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, llvm-tools
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - name: Build rustup target
      if: ${{ matrix.arch != 'riscv64' }}
      run: rustup target add ${{ matrix.arch }}-unknown-linux-musl
    - name: Run tests for musl applications
      run: make test ARCH=${{ matrix.arch }}

  test-oscomp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64, loongarch64]
        rust-toolchain: [nightly-2025-01-18]
    env:
      qemu-version: 9.2.1
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, llvm-tools
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - name: Build python environment
      run: sudo apt-get install -y python3 python3-pip
    - name: Run tests for oscomp musl testcases
      run: make oscomp_test ARCH=${{ matrix.arch }} LIBC=musl
    - name: Run tests for oscomp glibc testcases
      run: make oscomp_test ARCH=${{ matrix.arch }} LIBC=glibc
